# Dependencies
# $ gem install rouge
# $ rougify style base16.solarized > assets/css/highlighter.css
highlighter: rouge

# Custom variables
repository: "https://github.com/vsn4ik/bootstrap-checkbox"
version: 2.0.0
name: "Bootstrap-checkbox"
description: "A checkbox component based on Bootstrap framework"
keywords: "bootstrap checkbox jquery-plugin switch"

author:
  name: "Vasilii A."

cdn:
  bootstrap:
    css: "https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.css"
    js: "https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.js"

  jquery:
    js: "https://code.jquery.com/jquery-3.6.3.slim.js"

  fa:
    css: "https://use.fontawesome.com/releases/v5.15.4/css/all.css"
