name: Run tests
on: [push, pull_request]

jobs:
  run:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@master
        with:
          fetch-depth: 3

      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          version: 12

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm install

      - name: Run tests
        run: npm run test
